name: ci

on: [workflow_dispatch, push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - windows-2019
          - windows-2022
          - windows-latest
          - ubuntu-latest
          - macos-latest
    name: "${{ matrix.platform }}"
    steps:
      - uses: actions/checkout@main

      #- name: Set up MSVC for Windows
      #  if: runner.os == 'Windows'
      #  uses: ilammy/msvc-dev-cmd@v1

      # - name: Setup interactive tmate session # uncomment this to get a remote shell to debug the build
      #   uses: mxschmitt/action-tmate@v3

      - name: Build
        shell: bash
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release

      - name: Run tests on Windows
        if: runner.os == 'Windows'
        shell: bash
        run: |
          ./Release/main.exe

      - name: Run tests on Unix-like systems
        if: runner.os != 'Windows'
        shell: bash
        run: |
          ./build/main
